on:
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Hello word
        run: echo Hello, world!
